### ISSUE TITLE
Добавить проверку на дубликаты правил

### ISSUE THREAD

**Issue by StApostol** [developeruz/yii2-db-rbac#10]
Upholding foreign key constraints for table 'auth_item', entry 'user/user/index', key 1 would lead to a duplicate entry

**Comment by developeruz** [comment]
Такая проверка уже есть: https://github.com/developeruz/yii2-db-rbac/blob/master/controllers/AccessController.php#L177  
Не могли бы вы по шагам расписать как вам удалось получить такую ошибку? У меня не получилось ее воспроизвести.

**Comment by StApostol** [comment]
Создаете 2 разных правила, заходите редактировать одно и меняете значение "Разрешенный доступ" на значение другого правила и нажимаете сохранить.

**Comment by StApostol** [comment]
Заментил после обновления до текущей версии ошибку в сохранении правил. Надо поменять кавычки с ' на " в этой строке https://github.com/developeruz/yii2-db-rbac/blob/master/controllers/AccessController.php#L201, а то он вместо обрезания переносов строк, обрезает символы
