### ISSUE TITLE
Столкнулся с проблемой данного модуля

### ISSUE THREAD

**Issue by i-coder** [developeruz/yii2-db-rbac#11]
Если сделать гибкое подключение в контролере
use developeruz\db_rbac\behaviors\AccessBehavior;
//поведение
public function behaviors()
return [
'as AccessBehavior' => [
'class' => AccessBehavior::className(),
],
yii2 выдает
Getting unknown property: backend\controllers\ManagerController::requestedAction

решил проблему так 
в поведении  public function interception($event)
//$event->sender->module->requestedAction;
$action = $event->sender->module->requestedAction;
так как объект возвращает  внутри модуля и просто перенаправил на ->module
и все заработало

**Comment by carlositos** [comment]
Точно такая же проблема. Решение $action = $event->sender->module;  помогло
