### ISSUE TITLE
Похоже проблема в actionUpdatePermission

### ISSUE THREAD

**Issue by sandrei** [developeruz/yii2-db-rbac#12]
В этом action из за проверки на уникальность по имени правила, невозможно записать изменения.

**Comment by developeruz** [comment]
Уточните пожалуйста ваш вопрос. Я не понимаю о чем вы.

**Comment by sandrei** [comment]
Такая проблема.
Открываю правило для редактирования. Вношу изменения в поле "Текстовое описание", созданного и сохраненного правила, при сохранении получаю исключение "Правило с таким именем уже существует".  т.е. изменить текстовое описание существующего правила невозможно.

**Comment by i-coder** [comment]
да да такая же проблема раньше не было этого!
Редактирование роли -> сохранить -> выдает
Роль с таким именем уже существует:admin

**Comment by i-coder** [comment]
public function actionUpdateRole($name)
решил проблему так 
&& $this->validate(Yii::$app->request->post('name'), $this->pattern4Role)
// && $this->isUnique(Yii::$app->request->post('name'), 'role') - раньше этого небыло глянул в историю и проканало =) и записи стали обновлятся

**Comment by developeruz** [comment]
Проблема решена. Проверка на уникальность теперь срабатывает, только если поле имени роли/правила поменялось.
