### ISSUE TITLE
Проблема с отображением страницы отказа

### ISSUE THREAD

**Issue by Alsodan** [developeruz/yii2-db-rbac#13]
Подключил поведение, проверяющее права "на лету" в конфиг приложения.
Теперь, если у пользователя нет прав или он не авторизирован получаю следующее:

An Error occurred while handling another error:
exception 'yii\web\BadRequestHttpException' with message 'Не достаточно прав' in C:\OpenServer\domains\etp\frontend\behaviors\AccessBehavior.php:48
Stack trace:
#0 [internal function]: frontend\behaviors\AccessBehavior->interception(Object(yii\base\ActionEvent))
#1 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent))
#2 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Module.php(607): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#3 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Controller.php(139): yii\base\Module->beforeAction(Object(yii\web\ErrorAction))
#4 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('error', Array)
#5 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\web\ErrorHandler.php(80): yii\base\Module->runAction('site/error')
#6 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\ErrorHandler.php(101): yii\web\ErrorHandler->renderException(Object(yii\web\BadRequestHttpException))
#7 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\BadRequestHttpException))
#8 {main}

Previous exception:
exception 'yii\web\BadRequestHttpException' with message 'Не достаточно прав' in C:\OpenServer\domains\etp\frontend\behaviors\AccessBehavior.php:48
Stack trace:
#0 [internal function]: frontend\behaviors\AccessBehavior->interception(Object(yii\base\ActionEvent))
#1 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent))
#2 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Module.php(607): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#3 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Controller.php(139): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#4 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('contact', Array)
#5 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('site/contact', Array)
#6 C:\OpenServer\domains\etp\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 C:\OpenServer\domains\etp\frontend\web\index.php(18): yii\base\Application->run()
#8 {main}

Добавление 'site/error' в правила не помогло.
'as AccessBehavior' => [
        'class' => \frontend\behaviors\AccessBehavior::className(),
        'rules' => [
            'site' => [
                [
                    'actions' => ['offer', 'index', 'error'],
                    'allow' => true,
                ],
            ],
        ],
    ],

**Comment by developeruz** [comment]
Исправлено

**Comment by Alsodan** [comment]
Проблема осталась.

**Comment by Alsodan** [comment]
Насколько я понимаю, проблема в том, что страница ошибки пытается отобразиться в роуте, к которому запрещен доступ. Пока использую неинформативную заглушку

if(!$this->cheсkByRule($action, $user, $request))
        {
            //И по AuthManager
            if(!$this->checkPermission($route))

```
            Yii::$app->response->redirect('/site/error');
    }
```

**Comment by html2php** [comment]
Подтверждаю, проблема существует. Решил добавлением переменной $count и в начале метода interception строк

``` php
        $this->count++;
        if ($this->count > 1) return;
```

Вероятно есть более правильный вариант
