### ISSUE TITLE
Текущие роли

### ISSUE THREAD

**Issue by Pashkinz92** [developeruz/yii2-db-rbac#14]
А как же просмотреть текущие роли пользователя?
Создавать отдельные модели для таблиц с ролями, и прописывать вручную связи в таблице пользователя?

**Comment by developeruz** [comment]
Yii::$app->authManager->getRolesByUser($userID) вернет роли, которые уже назначены юзеру
getPermissionsByUser() - аналогично для пермишенов. Все уже придумано до нас :)

**Comment by Pashkinz92** [comment]
то-то же ) знаю, что придумано, и свой велосипед делать не стоит ) спасибо )
