### ISSUE TITLE
The use statement with non-compound name 'Yii' has no effect

### ISSUE THREAD

**Issue by martrix78** [developeruz/yii2-db-rbac#19]
Добрый день,
После какого то обновления начали выскакивать везде подобные ворнинги на 
"use Yii;"
в вьюхах
если указать абсолютное определение NS (use \Yii;) то все нормально

**Comment by developeruz** [comment]
Проблема была в отсутствии namespace во view файлах. Исправлена в версии 1.0.8. Обновитесь пожалуйста еще раз.
