### ISSUE TITLE
Как создать premission со значением Name = "my-controller/action"

### ISSUE THREAD

**Issue by godscreature** [developeruz/yii2-db-rbac#2]
Здравствуйте. Очень помог ваш модуль. Спасибо.

Но существует один нюанс:
У меня контроллер зовется "TicketMessageController", и если взять, к примеру actionIndex, то в адресной строке будет такое: "http://domain.ru/admin/my-controller/index".

Проблема в том, что валидатор поля Name при создании Premission не пропускает дефисы((
Я не могу задать Name = "my-controller/index"

Было бы здорово, если бы у вас нашлось немного времени допилить эту штуку.

**Comment by developeruz** [comment]
Спасибо за то, пользуетесь моим модулем. Ошибку вроде исправила.
