### ISSUE TITLE
Правила не применяются при POST запросе

### ISSUE THREAD

**Issue by martrix78** [developeruz/yii2-db-rbac#20]
сделал правило publish/index 
все отображается.
Однако если в гриде жму на удалить запись, то запись спокойно удаляется :(
UPD, action Create тоже работает.
Такое впечатление, что правила начинают работать только при рендеринге вьюшки.

**Comment by developeruz** [comment]
У вас точно самая свежая версия модуля? Обновитесь до последней версии.

**Comment by martrix78** [comment]
./composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Removing phpoffice/phpexcel (1.8.0)  
- Installing phpoffice/phpexcel (1.8.1)
  Downloading: 100%         
- Updating kartik-v/yii2-grid (dev-master 7ed8d38 => v3.0.7)
  Checking out 913fde8fbe41bf998d53a88d0443e25e1e696194
- Removing kartik-v/yii2-export (v1.2.2)
- Installing kartik-v/yii2-export (v1.2.3)
  Downloading: 100%  

Writing lock file
Generating autoload files

**Comment by developeruz** [comment]
Хорошо, я проверю. Спасибо что сказали, если вы правы - то это огромнейший баг.

**Comment by martrix78** [comment]
пожалуйста. У меня еще стоят экстеншены
"dektrium/yii2-user": "0.9.*@dev",
"dektrium/yii2-rbac": "dev-master", 
но контроль доступа же идет через developeruz\db_rbac\behaviors\AccessBehavior
так что думаю эти расширения тут не при чем

**Comment by developeruz** [comment]
Сгенерировала CRUD через gii, повесила поведение, прописала правило - итог: все работает правильно. За другие модули отвечать не могу, т.к не знаю как они работают. К сожалению, это все чем могу помочь.
