### ISSUE TITLE
проверка прав из конфига

### ISSUE THREAD

**Issue by mindochin** [developeruz/yii2-db-rbac#23]
в конфиге приложения, в поведении прописан доступ к контроллеру order админу
'order'=> [['allow'=>true, 'roles'=>['admin']]]
в меню стоит проверка
'visible' => Yii::$app->user->can('order')
и проверка не проходит - пункт меню не виден. куда копать?
админ конечно же залогинен

**Comment by developeruz** [comment]
То правило, что вы прописали в конфиге поведения используется только поведением для решения давать доступ или нет. Поведение создает из этого конфига правила, но не сохраняет их как роли и права у юзера. Т.е за пределами поведения этого правила нигде нет. 
Вы можете добавить это правило динамически, через веб-интерфейс. Модуль подцепит вашу роль admin, привяжите к ней доступ к "order" (через веб интерфейс пропишите "order" в "Разрешенный доступ"). Тогда Yii::$app->user->can('order') будет работать.
