### ISSUE TITLE
Присвоение роли при регистрации.

### ISSUE THREAD

**Issue by Sorny-net** [developeruz/yii2-db-rbac#24]
Здравствуйте. При регистрации пользователя возникла проблема:

Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null
The SQL being executed was: INSERT INTO `auth_assignment` (`user_id`, `item_name`, `created_at`) VALUES (NULL, 'customer', 1448345423)

Error Info: Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'user_id' cannot be null
)

↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null

in C:\xampp\htdocs\vendor\yiisoft\yii2\db\Command.php at line 781

В models\SignupForm.php

public function signup()
    {
        if ($this->validate()) {
            $user = new User();
            $user->username = $this->username;
            $user->email = $this->email;
            $user->setPassword($this->password);
            $user->status = User::STATUS_WAIT;
            $user->generateAuthKey();
            $user->generateEmailConfirmToken();
            $userRole = Yii::$app->authManager->getRole('customer');
            Yii::$app->authManager->assign($userRole, $user->getId());
            if ($user->save()) {
                Yii::$app->mailer->compose('@app/models/emailConfirm', ['user' => $user])
                    ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->name])
                    ->setTo($this->email)
                    ->setSubject('Email confirmation for ' . Yii::$app->name)
                    ->send();
            }

```
        return $user;
    }

    return null;
}
```

где customer одна из ролей. Полный текст ошибки http://pastebin.ru/vL2crL8O
Роли созданы. Что я делаю не так?

**Comment by developeruz** [comment]
Пока вы не сохранили user-а метод getId() возвращает null. 
Перенесите кусок, отвечающий за присвоение роли внутрь if ($user->save()) {

**Comment by Sorny-net** [comment]
Спасибо!
