### ISSUE TITLE
При изменении permissions у роли, стираются наследования роль от роли

### ISSUE THREAD

**Issue by noel-ykt** [developeruz/yii2-db-rbac#25]
Например у меня есть две роли "admin" и "user".
- вручную добавил наследования admin от user.

```
$roleAdmin = Yii::$app->authManager->getRole('admin');
$roleUser = Yii::$app->authManager->getRole('user');
Yii::$app->authManager->addChild($roleAdmin, $roleUser);
```
- с помощью уже готовых форм (в вашем модуле), создал разрешения и распределил по ролям
- в результате удалилась запись наследования admin от user
- ожидалось что все записи наследования должны тоже остаться в БД, но их нет

**Comment by developeruz** [comment]
Да, есть такое: https://github.com/developeruz/yii2-db-rbac/blob/master/controllers/AccessController.php#L91 Удаляются все связи, т.к если чекбокс с разрешением был ранее отмечен, а потом отметку убрали, отловить этот момент практически не возможно. Можно добавить префикс ко всем разрешениям, созданным через веб-интерфейс и удалять только их, но сейчас это поломает обратную совместимость с текущей версией. Вариант решения вашей проблемы: проверять в поведении приложения, есть ли связь (hasChild ) и восстанавливать ее если нет.

**Comment by luciuz** [comment]
Ждем версию 2.0, где не нужно будет заботиться о совместимости и все будет работать как нужно.

**Comment by developeruz** [comment]
Исправила, спасибо за терпение :)
