### ISSUE TITLE
Аction только для авторизованных возвращает 403

### ISSUE THREAD

**Issue by luciuz** [developeruz/yii2-db-rbac#26]
До подключения поведения action только для авторизованных `'roles' => ['@']` редиректил на страницу логина. А сейчас возвращает 403.

**Comment by developeruz** [comment]
Поведение бросает эксепшен, как его обрабатывать - решает ваше приложение. 
Но у многих проблема с обработкой эксепшенов, поэтому добавила в поведение два параметра: 

``` php
    'as AccessBehavior' => [
        'class' => AccessBehavior::className(),
        'redirect_url' => '/forbidden',
        'login_url' => Yii::$app->user->loginUrl
    ]
```

Оба параметра не обязательные, login_url влияет только на не авторизованного пользователя. Если задан redirect_url - в случаи отсутствия доступа будет редирект на этот url, если нет то экспешен. Надеюсь вам это тоже поможет.
