### ISSUE TITLE
дефолтные правила в конфиге для модулей

### ISSUE THREAD

**Issue by martrix78** [developeruz/yii2-db-rbac#3]
Добрый день, 
как подружить ваш модуль с Yii2-user?
Например у регистрации пользователя там такой путь "user/registration/register"
пишу :
'user' => [
    'registration'=> [
            'actions' => ['login', 'register'],
             'allow' => true,  
             ]
    ],
],
не работает
                'user' => [
                    [
                    'actions' => ['registration/register', 'login', 'register'],
                    'allow' => true,  
                    ]
                ],
То же самое :(
как быть?

**Comment by developeruz** [comment]
В данном случаи user - это модуль, registration -  контроллер и register - action. В правилах, если вы прописываете их в конфиге, модуль нужно указывать вместе с контроллером:

``` php
'user/registration' => [
[
'actions' => ['login', 'register'],
'allow' => true,
]
],
```

**Comment by martrix78** [comment]
Спасибо большое :)
А то сижу голову ломаю
