### ISSUE TITLE
Ошибка добавления одноименных разрешений и ролей

### ISSUE THREAD

**Issue by TwoNotTwo** [developeruz/yii2-db-rbac#30]
Если попытаться добавить одноименную с разрешением роль или наоборот, то появляется ошибка дубликатов записей в таблице auth_item. 
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'user' for key 'PRIMARY'`

Ошибка возникает из-за частично неправильного алгоритма функции isUnique($name, $type) в контроллере db_rbac/controllers/AccessController. В исходном алгоритме проверка основана на типе записи (type), которую нужно добавить в БД и последующей проверки на принадлежность к классу Permission или Role. 

```
 protected function isUnique($name, $type)
    {
        if ($type == 'role') {
            $role = Yii::$app->authManager->getRole($name);
            if ($role instanceof Role) {
                $this->error[] = Yii::t('db_rbac', 'Роль с таким именем уже существует: ') . $name;
                return false;
            } else return true;
        } elseif ($type == 'permission') {
            $permission = Yii::$app->authManager->getPermission($name);
            if ($permission instanceof Permission) {
                $this->error[] = Yii::t('db_rbac', 'Правило с таким именем уже существует: ') . $name;
                return false;
            } else return true;
        }
    }
```

Такая защита срабатывает только если имя нового разрешения совпадает с уже имеющимися разрешениями (аналогично с ролями), но не дает нужного результата, если, например, попытаться создать роль одноименную с уже имеющимся разрешением (и наоборот).

Данную ошибку я исправил следующим алгоритмом:

```
protected function isUnique($name)
{
        $role = Yii::$app->authManager->getRole($name);
        $permission = Yii::$app->authManager->getPermission($name);
        if ($permission instanceof Permission){
            $this->error[] = Yii::t('db_rbac', 'Разрешение с таким именем уже существует') .':'. $name;
            return false;
        }
        if ($role instanceof Role) {
            $this->error[] = Yii::t('db_rbac', 'Роль с таким именем уже существует') .':'. $name;
            return false;
        }
        return true;
}
```

Прошу рассмотреть предложенный алгоритм и, возможно, использовать его как вариант доработки.

Отдельное спасибо за Ваш модуль динамической настройки доступа

**Comment by developeruz** [comment]
Исправлено, спасибо. 
PS: Буду признательна, если сможете оформить все исправления текстовок модуля в виде пул-реквеста (видела что вы исправляли в своем форке)
