### ISSUE TITLE
Устанавливаю yii2-db-rbac на yii2 basic и сыпятся ошибки

### ISSUE THREAD

**Issue by i-coder** [developeruz/yii2-db-rbac#32]
Пробуем permit/access/role выдает ниже
PHP Fatal Error – yii\base\ErrorException
Call to a member function getRoles() on a non-object
[http://joxi.ru/EA4npplFDRQGzm](url)

**Comment by developeruz** [comment]
У вас не настроен authManager 
Для корректной работы модуля необходимо настроить authManager в конфиге приложения (common/config/main.php для advanced или config/web.php и config/console для basic приложения)

```
'components' => [
   'authManager' => [
      'class' => 'yii\rbac\DbManager',
    ],
...
]
```

И выполнить миграции, создающие таблицы для DbManager (подразумевается, что коннект к БД для приложения уже настроен)

$ yii migrate --migrationPath=@yii/rbac/migrations/

**Comment by i-coder** [comment]
Спасибо за оперативность ! Спасибо помогло!
