### ISSUE TITLE
Странно но по обращение к пользователю permit/user/view?id=3

### ISSUE THREAD

**Issue by i-coder** [developeruz/yii2-db-rbac#33]
Not Found (#404)
код старый может в этом проблема? Просто хотел роли раскидать на старую систему

**Comment by developeruz** [comment]
Если версия модуля старая, та что без юзера еще, то может быть. Но скорее всего проблема в марштурах. Т.е нужно проверять свой urlManager

**Comment by i-coder** [comment]
ну в принципе вот как обычно
[http://joxi.ru/Dr8WnnqtkbO3kA](url)

**Comment by developeruz** [comment]
'modules' => [
        'permit' => [
            'class' => 'developeruz\db_rbac\Yii2DbRbac',
        ],
    ],
