### ISSUE TITLE
Закрытие модуля через Rules 

### ISSUE THREAD

**Issue by AntonNatarov** [developeruz/yii2-db-rbac#34]
Добрый день, подскажите пожалуйста как можно закрыть доступ на
/permit/access/role - управление ролями
/permit/access/permission - управление правами доступа
поскольку юзеры не имеют доступ к другим частям админки,а по этим ссылкам могут попасть. Или каким образом можно закрыть админку полностью использую Advanced архитектуру.

Я пробовал задать динамическое поведение в контроллерах в вендоре.  На Access и User контроллер соответственно + пермишн правила через модуль, но доступа не имею.

делал нативным простым способом(удалил все правила ранее)
`'rules' =>
                    ['adress' =>
                        [
                            [
                                'actions' => ['add-role', 'update-role'],
                                'allow' => true,
                                'roles' => ['admin'],
                            ],
                        ]
                    ]`

Но имея роль я все равно не получаю доступа к нужным экшенам. В других местах работает все хорошо.

**Comment by developeruz** [comment]
Закрыть доступ к модулю можно либо:
- с помощью динамического поведения, установив и настроив его как описано в описании
- отнаследовав нужные контроллеры, прописать туда access control обычным способом.
  Менять что-либо в папке vendor плохая идея, т.к эти изменения затрутся при следующем апдейте.
