### ISSUE TITLE
Вопрос как модуль по ведет себя ?

### ISSUE THREAD

**Issue by i-coder** [developeruz/yii2-db-rbac#35]
Суть такая, есть backend и frontend - там и там есть Контролер (User)
Если я выставлю права Разрешить в frontend то он сможет и в backend работать с этим Контролером?

**Comment by developeruz** [comment]
Модуль базируется на правилах роутинга. У вас в принципе не может быть одинакового пути для разных контроллеров, т.е путь "/user" не может сразу указывать и на бекенд-контроллер и на фронт-контроллер. Модуль проверяет есть ли у юзера право доступа к данному пути, а не контроллеру.
