### ISSUE TITLE
Пожалуйста добавьте возможность перевода с базы

### ISSUE THREAD

**Issue by bodasia** [developeruz/yii2-db-rbac#37]
В фале https://github.com/developeruz/yii2-db-rbac/blob/master/Yii2DbRbac.php
переписать ф-ю на
public function registerTranslations()
    {
        if (!isset(Yii::$app->get('i18n')->translations['db_rbac'])) {
            Yii::$app->i18n->translations['db_rbac'] = [
                'class' => 'yii\i18n\PhpMessageSource',
                'sourceLanguage' => 'ru-Ru',
                'basePath' => '@developeruz/db_rbac/messages',
            ];
        }
    }

**Comment by Beaten-Sect0r** [comment]
Много фраз не переведено

**Comment by developeruz** [comment]
Вы абсолютно правы. Исправила. Спасибо за терпение :)
