### ISSUE TITLE
Не срабатывает роль по-умолчанию

### ISSUE THREAD

**Issue by quinlena** [developeruz/yii2-db-rbac#38]
Здравствуйте! В конфиге пишу:

`'authManager' => [
          'class' => 'yii\rbac\DbManager',
          'defaultRoles' => 'guest',
        ]`
Но правила для guest не применяются. Как быть?

**Comment by developeruz** [comment]
Расскажите пожалуйста подробнее что делаете? Есть ли в базе роль guest или она польностью виртуальная? Если виртуальная, то как вы привязываете правило к такой роли?

**Comment by quinlena** [comment]
В базе есть роль guest, к ней привязаны правила. Заметила, что такая проблема, если контроллеры во фронтенде и бэкенде называются одинаково.
