### ISSUE TITLE
Очень серьёзный баг

### ISSUE THREAD

**Issue by shoxabbos** [developeruz/yii2-db-rbac#50]
Спокойно можно получить доступ к любому защищенному маршруту через двойной слэш.

**Comment by dastanaron** [comment]
//If the path at the beginning contains a slash, then a redirect to it to cut off the slash
        if(preg_match('#^[/](.*)#', $route[0], $match)) {
            Yii::$app->response->redirect($match[0])->send();
        }
  Сделал пул запрос с таким примером. Может есть идея лучшей реализации, я так на скорую мысль так сказать. Если есть, то будем ждать изменений

**Comment by shoxabbos** [comment]
После этого бага я удалил пакет из проекта )) Потому что было очень стыдно перед клиентом ...

**Comment by dastanaron** [comment]
Ну наверное так категорично не стоило. Проект хорош. Самому долго RBAC настраивать. Запросы только не очень оптимизированы, но это скорее к самому Yii2 претензия, потому что при проверке can(), он делает 3 или 4 запроса, не помню точно, а так в целом, не плохо. Баг можно было и костыльно исправить. Всего не предусмотришь. Мне лично интерфейс не нравится, поэтому форкнул себе и переделал интерфейс маленько и баг этот поправил, но в целом, девушке-респект.

**Comment by developeruz** [comment]
@shoxabbos расскажите как воспроизвести баг? У меня не воспроизводится. Куда именно вы добавили двойной слеш?

**Comment by shoxabbos** [comment]
www.site.com//admin

**Comment by developeruz** [comment]
Добавила фикс и сделала релиз, проверьте пожалуйста.

**Comment by shoxabbos** [comment]
Rahmat ))

**Comment by developeruz** [comment]
@dastanaron не хотите сделать PR или описать как можно улучшить UI? Судя по вашему форку  вы добавили возможность загружать правила из файла. Классная и наверное полезная фича. С радостью рассмотрю PR 👍

**Comment by hryvinskyi** [comment]
@developeruz c урлом www.site.com//admin ваш фикс работает, но с www.site.com//////admin уже нет.
Лучше вместо trim пройтись по всему урлу preg_replace('#/+#','/', $url);

**Comment by developeruz** [comment]
@scriptua у меня баг не воспроизводится и с site.com//admin, поэтому сложно проверить, что работает а что нет. По умолчанию в Yii ``Yii::$app->user->can('')`` возвращает false, т.е проблем быть не должно и с пустыми слешами. Проверьте пожалуйста что у вас возвращает ``Yii::$app->user->can('')`` и что у вас в `yii\web\User` `_access`?

**Comment by dastanaron** [comment]
@developeruz Из файла это не правила, а настройки. Суть следующая: чтобы не писать каждый раз разрешение новому контроллеру, например articles/index | articles/create и т.д. Программист по мере добавления новых контроллеров, добавляет их в yaml конфиг (yaml в данном случае немного удобнее обычного массива и в средах разработке, сразу выделяется среди других). Yaml встроен в yii вместе с symfony компонентами, поэтому сложности в этом нет. Потом выбор правил проводится с помощью select2, этот же модуль включен для выбора готовых правил для ролей и т.д. Это намного удобнее, чем чекбоксы. Теперь этот модуль имеет две зависимости для композера:
requires

yiisoft/yii2: *
kartik-v/yii2-widget-select2: ^2.1

Я использую select2 от kartik-v, поскольку он наиболее поддерживаемый. Сильно ничего не менял, пока тоже идей нет, использую для одного текущего проекта, со своими переделками, поэтому и форкнул его себе. По мере новых идей, буду внедрять, если будет что-то полезное для всех, напишу вам, может вы тоже реализуете

Насчет вашего решения по устранению бага.
Мне нравится, я также сделал, покрасивее, чем регулярка, у меня работает нормально, три слэша и более, как пишут далее, по идее должны отдавать 404, а двойной должен работать. Поэтому ваше решение вполне себе. Может еще выявится чего, посмотрим, если буду исправлять у себя, буду делать пулы вам тоже
