### ISSUE TITLE
Super Admin

### ISSUE THREAD

**Issue by nick7chasnyi** [developeruz/yii2-db-rbac#52]
Привет.
Как создать через админку правило (роль) для доступа ко всем модулям и контролерам, так сказать создать роль суперадмина?
Спасибо.

**Comment by dastanaron** [comment]
Одним разрешением никак. Но можно на все контроллер объявить правило доступа ко всем методам. 
Например если есть контроллер ArticleController и NewsController, вы можете объявить два правила article и news и присвоить эти правила роли super admin

https://imgur.com/a/j6ROb

**Comment by nick7chasnyi** [comment]
Спасибо за ответ.
