### ISSUE TITLE
Не работает при использовании runAction()

### ISSUE THREAD

**Issue by letstestcode** [developeruz/yii2-db-rbac#55]
Например, есть 2 контроллера, оба находятся в модуле, который под AccessBehavior. Если мы в экшене первого котроллера запускаем action второго контроллера через Yii::$app->runAction($route), то правила проверяются дважды, как и ожидается, но оба раза они проверяются для одного и того же экшена первого контроллера. 

Дело в том, что при runAction() не меняется значение из Yii::$app->getRequest()->resolve(). Уж не знаю, баг это yii2 или так и должно быть.

**Comment by developeruz** [comment]
К сожалени, я думаю это не возможно исправить в моем модуле. Модуль работать по url-ам и поэтому использует Yii::$app->getRequest()->resolve(). Можно попробовать открыть issue в репозитории Yii и если это баг его поправят и все заработает как надо.

**Comment by letstestcode** [comment]
В самом фреймворке это не считают багом. https://github.com/yiisoft/yii2/issues/16585
