### ISSUE TITLE
при вставке в меню не может найти вью

### ISSUE THREAD

**Issue by des1roer** [developeruz/yii2-db-rbac#6]
Invalid Parameter – yii\base\InvalidParamException
The view file does not exist: D:\open\OpenServer\domains\localhost\yii2rbac\backend\views\layouts\/admin.php

\localhost\yii2rbac\backend\views\layouts\main.php

```
  $menuItems = [
            ['label' => 'front', 'url' => 'http://localhost/yii2rbac/frontend/web/index.php' ],
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'role', 'url' => ['/permit/access/role']],
            ['label' => 'permission', 'url' => ['/permit/access/permission']],
```

**Comment by des1roer** [comment]
перед этим нужно закоментить лэйаут
    'modules' => [
        'permit' => [
            'class' => 'developeruz\db_rbac\Yii2DbRbac',
           // 'layout' => '//admin'
        ],
    ],

**Comment by developeruz** [comment]
Отсутсвие файла layout это только ваша проблема, "admin" прописан для примера. Удалите эту строку или пропишите существующий layout. К ошибкам модуля это не относится.
