### ISSUE TITLE
Как создавать правила для подмодулей

### ISSUE THREAD

**Issue by StApostol** [developeruz/yii2-db-rbac#9]
У Вас есть код  в AccessBehavior, который ограничивается только модулем
<code>
$routePathTmp = explode('/', $route[0]);
        if(count($routePathTmp) == 3)
        {
           ....
        }
        elseif(count($routePathTmp) == 2) {
           ....
       }
        else {
            ...
        }
</code>

Может переписать на какую-нибудь рекурсию, что-то типа вызов метода с передачей массива который implode через /, удаление последнего элемента и опять implode

**Comment by developeruz** [comment]
Спасибо за ценные предложения!
